
default_fields = {
    1: [
        {"pontuacao_fixa": 100, "titulo": "Spyglass"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Ingredient"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Metal"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Oil"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Ingredient"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Metal"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Oil"},
        {"pontuacao_fixa": 100*5, "titulo": "5 min Construction Speed Up"},
        {"pontuacao_fixa": 100*60, "titulo": "1 hr Construction Speed Up"},
        {"pontuacao_fixa": 100, "titulo": "1 min Construction Speed Up"},
        {"pontuacao_fixa": 2000, "titulo": "UnderSEa Cavern"},
        {"pontuacao_fixa": 30, "titulo": "Diamond"},
    ],
    2: [
        {"pontuacao_fixa": 1, "titulo": "Treasure Blueprint"},
        {"pontuacao_fixa": 1/100, "titulo": "Intel"},
        {"pontuacao_fixa": 2000, "titulo": "Crimson Depths"},
        {"pontuacao_fixa": 30, "titulo": "Diamond"},
    ],
    3: [
        {"pontuacao_fixa": 300, "titulo": "Turbo Engine"},
        {"pontuacao_fixa": 3000, "titulo": "Reflit Frigate"},
        {"pontuacao_fixa": 50, "titulo": "Weapon Draw"},
        {"pontuacao_fixa": 50, "titulo": "Hero Draw"},
        # {"pontuacao_fixa": 1, "titulo": "Time to speed Up Forge"},
        {"pontuacao_fixa": 100*5, "titulo": "5 min Forge Speed Up"},
        {"pontuacao_fixa": 100*60, "titulo": "1 hr Froge Speed Up"},
        {"pontuacao_fixa": 100, "titulo": "1 min Forge Speed Up"},
        {"pontuacao_fixa": 2000, "titulo": "Radiation Bay"},
        {"pontuacao_fixa": 30, "titulo": "Diamond"},
    ],
    4: [
        {"pontuacao_fixa": 1/100, "titulo": "Chemical"},
        {"pontuacao_fixa": 100*5, "titulo": "5 min Chemical Speed Up"},
        {"pontuacao_fixa": 100*60, "titulo": "1 hr Chemical Speed Up"},
        {"pontuacao_fixa": 100, "titulo": "1 min Chemical Speed Up"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Ingredient"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Metal"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Oil"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Ingredient"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Metal"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Oil"},
        {"pontuacao_fixa": 30, "titulo": "Diamond"},
    ],
    5: [
        {"pontuacao_fixa": 100, "titulo": "Spyglass"},
        {"pontuacao_fixa": 50, "titulo": "Weapon Draw"},
        {"pontuacao_fixa": 50, "titulo": "Hero Draw"},
        # {"pontuacao_fixa": 1, "titulo": "Time to speed Up Forge"},
        {"pontuacao_fixa": 100*5, "titulo": "5 min Forge Speed Up"},
        {"pontuacao_fixa": 100*60, "titulo": "1 hr Froge Speed Up"},
        {"pontuacao_fixa": 100, "titulo": "1 min Forge Speed Up"},
        {"pontuacao_fixa": 2000, "titulo": "Pirate's Lair"},
        {"pontuacao_fixa": 30, "titulo": "Diamond"},
    ],
    6: [
        {"pontuacao_fixa": 300, "titulo": "Turbo Engine"},
        {"pontuacao_fixa": 3000, "titulo": "Reflit Frigate"},
        {"pontuacao_fixa": 1/100, "titulo": "Intel"},
        {"pontuacao_fixa": 2000, "titulo": "UnderSea Cavern"},
        {"pontuacao_fixa": 30, "titulo": "Diamond"},
    ],
    7: [
        # {"pontuacao_fixa": 1, "titulo": "Time to speed Up Forge"},
        {"pontuacao_fixa": 100*5, "titulo": "5 min Forge Speed Up"},
        {"pontuacao_fixa": 100*60, "titulo": "1 hr Froge Speed Up"},
        {"pontuacao_fixa": 100, "titulo": "1 min Forge Speed Up"},
        {"pontuacao_fixa": 50, "titulo": "Weapon Draw"},
        {"pontuacao_fixa": 50, "titulo": "Hero Draw"},
        {"pontuacao_fixa": 1, "titulo": "Treasure Blueprint"},
        {"pontuacao_fixa": 1/100, "titulo": "Intel"},
        {"pontuacao_fixa": 1/100, "titulo": "Chemical"},
        {"pontuacao_fixa": 100*5, "titulo": "5 min Chemical Speed Up"},
        {"pontuacao_fixa": 100*60, "titulo": "1 hr Chemical Speed Up"},
        {"pontuacao_fixa": 100, "titulo": "1 min Chemical Speed Up"},
        {"pontuacao_fixa": 100, "titulo": "Spyglass"},
        {"pontuacao_fixa": 300, "titulo": "Turbo Engine"},
        {"pontuacao_fixa": 3000, "titulo": "Reflit Frigate"},
        {"pontuacao_fixa": 2000, "titulo": "Pirate's Lair"},
        {"pontuacao_fixa": 2000, "titulo": "UnderSea Cavern"},
        {"pontuacao_fixa": 2000, "titulo": "Crimson Depths"},
        {"pontuacao_fixa": 2000, "titulo": "Radiation Bay"},
        {"pontuacao_fixa": 2000, "titulo": "Storm Front"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Ingredient"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Metal"},
        {"pontuacao_fixa": 1/600, "titulo": "Construction Oil"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Ingredient"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Metal"},
        {"pontuacao_fixa": 1/600, "titulo": "Upgrade Construction Oil"},
        {"pontuacao_fixa": 30, "titulo": "Diamond"},
    ],

}

def add_default_fields(page_num, page_obj):
    fields = default_fields.get(page_num, [])
    for field in fields:
        page_obj.adicionar_campo(**field)
