default_fields = {
    1: [
        {"fixed_score": 100, "title": "Spyglass"},
        {"fixed_score": 1/600, "title": "Construction Ingredient"},
        {"fixed_score": 1/600, "title": "Construction Metal"},
        {"fixed_score": 1/600, "title": "Construction Oil"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Ingredient"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Metal"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Oil"},
        {"fixed_score": 100*5, "title": "5 min Construction Speed Up"},
        {"fixed_score": 100*60, "title": "1 hr Construction Speed Up"},
        {"fixed_score": 100, "title": "1 min Construction Speed Up"},
        {"fixed_score": 2000, "title": "UnderSea Cavern"},
        {"fixed_score": 30, "title": "Diamond"},
    ],
    2: [
        {"fixed_score": 1, "title": "Treasure Blueprint"},
        {"fixed_score": 1/100, "title": "Intel"},
        {"fixed_score": 2000, "title": "Crimson Depths"},
        {"fixed_score": 30, "title": "Diamond"},
    ],
    3: [
        {"fixed_score": 300, "title": "Turbo Engine"},
        {"fixed_score": 3000, "title": "Reflit Frigate"},
        {"fixed_score": 50, "title": "Weapon Draw"},
        {"fixed_score": 50, "title": "Hero Draw"},
        # {"fixed_score": 1, "title": "Time to speed Up Forge"},
        {"fixed_score": 100*5, "title": "5 min Forge Speed Up"},
        {"fixed_score": 100*60, "title": "1 hr Forge Speed Up"},
        {"fixed_score": 100, "title": "1 min Forge Speed Up"},
        {"fixed_score": 2000, "title": "Radiation Bay"},
        {"fixed_score": 30, "title": "Diamond"},
    ],
    4: [
        {"fixed_score": 1/100, "title": "Chemical"},
        {"fixed_score": 100*5, "title": "5 min Chemical Speed Up"},
        {"fixed_score": 100*60, "title": "1 hr Chemical Speed Up"},
        {"fixed_score": 100, "title": "1 min Chemical Speed Up"},
        {"fixed_score": 1/600, "title": "Construction Ingredient"},
        {"fixed_score": 1/600, "title": "Construction Metal"},
        {"fixed_score": 1/600, "title": "Construction Oil"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Ingredient"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Metal"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Oil"},
        {"fixed_score": 30, "title": "Diamond"},
    ],
    5: [
        {"fixed_score": 100, "title": "Spyglass"},
        {"fixed_score": 50, "title": "Weapon Draw"},
        {"fixed_score": 50, "title": "Hero Draw"},
        # {"fixed_score": 1, "title": "Time to speed Up Forge"},
        {"fixed_score": 100*5, "title": "5 min Forge Speed Up"},
        {"fixed_score": 100*60, "title": "1 hr Forge Speed Up"},
        {"fixed_score": 100, "title": "1 min Forge Speed Up"},
        {"fixed_score": 2000, "title": "Pirate's Lair"},
        {"fixed_score": 30, "title": "Diamond"},
    ],
    6: [
        {"fixed_score": 300, "title": "Turbo Engine"},
        {"fixed_score": 3000, "title": "Reflit Frigate"},
        {"fixed_score": 1/100, "title": "Intel"},
        {"fixed_score": 2000, "title": "UnderSea Cavern"},
        {"fixed_score": 30, "title": "Diamond"},
    ],
    7: [
        # {"fixed_score": 1, "title": "Time to speed Up Forge"},
        {"fixed_score": 100*5, "title": "5 min Forge Speed Up"},
        {"fixed_score": 100*60, "title": "1 hr Forge Speed Up"},
        {"fixed_score": 100, "title": "1 min Forge Speed Up"},
        {"fixed_score": 50, "title": "Weapon Draw"},
        {"fixed_score": 50, "title": "Hero Draw"},
        {"fixed_score": 1, "title": "Treasure Blueprint"},
        {"fixed_score": 1/100, "title": "Intel"},
        {"fixed_score": 1/100, "title": "Chemical"},
        {"fixed_score": 100*5, "title": "5 min Chemical Speed Up"},
        {"fixed_score": 100*60, "title": "1 hr Chemical Speed Up"},
        {"fixed_score": 100, "title": "1 min Chemical Speed Up"},
        {"fixed_score": 100, "title": "Spyglass"},
        {"fixed_score": 300, "title": "Turbo Engine"},
        {"fixed_score": 3000, "title": "Reflit Frigate"},
        {"fixed_score": 2000, "title": "Pirate's Lair"},
        {"fixed_score": 2000, "title": "UnderSea Cavern"},
        {"fixed_score": 2000, "title": "Crimson Depths"},
        {"fixed_score": 2000, "title": "Radiation Bay"},
        {"fixed_score": 2000, "title": "Storm Front"},
        {"fixed_score": 1/600, "title": "Construction Ingredient"},
        {"fixed_score": 1/600, "title": "Construction Metal"},
        {"fixed_score": 1/600, "title": "Construction Oil"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Ingredient"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Metal"},
        {"fixed_score": 1/600, "title": "Upgrade Construction Oil"},
        {"fixed_score": 30, "title": "Diamond"},
    ],
}

def add_default_fields(page_num, page_obj):
    fields = default_fields.get(page_num, [])
    for field in fields:
        page_obj.add_field(**field)
